### ISSUE TITLE
Params.cycles_refunded is not initialized

### ISSUE THREAD

**Issue by ulan** [dfinity/interface-spec#41]
The `cycles_refunded` field of `Params` is not initialized to the actual value of refunded cycles.

```
Params = {
  data : NoData | Blob;
  caller : NoCaller | Principal;
  reject_code : 0 | SYS_FATAL | SYS_TRANSIENT | …;
  reject_message : Text;
  sysenv : Env;
  cycles_refunded : Nat;
  method_name : Text;
}
```

**Comment by nomeata** [comment]
Indeed, how did that happen.

The refunded cycles are put on the
```
EntryPoint
  = PublicMethod MethodName Principal Blob
  | Callback Callback Response RefundedCycles
  | Heartbeat
```
then https://github.com/dfinity/interface-spec/blob/master/spec/index.adoc#message-execution we pass that to `Mod.callbacks` (And it would be helpful to have better variable names there):
```
    ( M.entry_point = Callback Callback Response Cycles
      F = Mod.callbacks(Callback, Response, Cycles, Env, Available)
    )
```
and that’s defined (in https://github.com/dfinity/interface-spec/blob/master/spec/index.adoc#the-concrete-canistermodule) to be
```
callbacks = λ(callbacks, response, sysenv, available) → λ wasm_state →
  let params0 = { empty_params with
    sysenv
    cycles_received = refund;
  }
```
and there it is is missing the `refund` parameter (although it is used) and seems to confuse `available` and `refundend` cycles. Ah, and `cycles_received` no longer exists, so that’s probably where the refactoring went wrong.

**Comment by ulan** [comment]
Thanks @nomeata! I'll prepare a fix
